"""Ajout du suivi des médicaments

Revision ID: 1e02428408b6
Revises: de83a6a7beff
Create Date: 2025-03-20 00:25:51.472683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e02428408b6'
down_revision = 'de83a6a7beff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication_taken', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('medication_last_updated', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('medication_last_updated')
        batch_op.drop_column('medication_taken')

    # ### end Alembic commands ###
