"""Ajout des champs last_seen et visit_count

Revision ID: 290ea024f62c
Revises: 
Create Date: 2025-03-17 18:46:43.795091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290ea024f62c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('visit_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('visit_count')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
