"""Add global_mood to User

Revision ID: de83a6a7beff
Revises: 4ce9177daee0
Create Date: 2025-03-18 22:06:51.271895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de83a6a7beff'
down_revision = '4ce9177daee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_mood_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('global_mood_updated_at')

    # ### end Alembic commands ###
