"""Ajout du suivi des médicaments

Revision ID: df8d74ca7116
Revises: fe81770f04d2
Create Date: 2025-03-20 09:47:48.529558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8d74ca7116'
down_revision = 'fe81770f04d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('medication_streak')

    # ### end Alembic commands ###
